name: 全部采集

on:
  schedule:
    - cron: '0 0 * * *' # 这是北京时间早上8点（UTC+8）
  workflow_dispatch:

jobs:
  run-1-py-daily:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: 设置 Python
      uses: actions/setup-python@v1
      with:
        python-version: '3.8'
    - name: 加载缓存
      uses: actions/cache@v2
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-
    - name: 安装依赖
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: 运行 1.py
      run: python 1.py
    - name: 上传 CSV 文件
      uses: actions/upload-artifact@v2
      with:
        name: daily_data
        path: daily_data_*.csv
