name: Run and Upload Script Output

on:
  push:
  schedule:
    - cron: '0 16 * * *' # 每天 UTC 时间 16:00 运行，对应北京时间 08:00

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: '3.8'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run script
      run: python your_script.py
    - name: Upload CSV file from your_script.py
      uses: actions/upload-artifact@v2
      with:
        name: gobrick_data
        path: gobrick_data_*.csv
    - name: Run script1
      run: python your_script1.py
    - name: Upload CSV file from your_script1.py
      uses: actions/upload-artifact@v2
      with:
        name: gobrick_detail
        path: gobrick_detail_*.csv
