name: 运行并上传脚本输出

on:
  workflow_dispatch:
    inputs:
      script_option:
        description: '选择要运行的脚本'
        required: true
        type: choice
        options:
          - 'your_script'
          - 'your_script1'

jobs:
  run-your-script:
    runs-on: ubuntu-latest
    if: ${{ github.event.inputs.script_option == 'your_script' }}
    steps:
    - uses: actions/checkout@v2
    - name: 设置 Python
      uses: actions/setup-python@v1
      with:
        python-version: '3.8'
    - name: 安装依赖
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: 运行脚本
      run: python your_script.py
    - name: 上传 CSV 文件
      uses: actions/upload-artifact@v2
      with:
        name: gobrick_data
        path: gobrick_data_*.csv

  run-your-script1:
    runs-on: ubuntu-latest
    if: ${{ github.event.inputs.script_option == 'your_script1' }}
    steps:
    - uses: actions/checkout@v2
    - name: 设置 Python
      uses: actions/setup-python@v1
      with:
        python-version: '3.8'
    - name: 安装依赖
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: 运行脚本1
      run: python your_script1.py
    - name: 上传 CSV 文件
      uses: actions/upload-artifact@v2
      with:
        name: gobrick_detail
        path: gobrick_detail_*.csv

    run-your-script2:
    runs-on: ubuntu-latest
    if: ${{ github.event.inputs.script_option == '1' }}
    steps:
    - uses: actions/checkout@v2
    - name: 设置 Python
      uses: actions/setup-python@v1
      with:
        python-version: '3.8'
    - name: 安装依赖
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: 运行脚本
      run: python your_script.py
    - name: 上传 CSV 文件
      uses: actions/upload-artifact@v2
      with:
        name: gobrick_data
        path: gobrick_data_*.csv
