name: 运行并上传脚本输出

on:
  workflow_dispatch:
    inputs:
      script_name:
        description: '要运行的脚本'
        required: true
        default: 'your_script.py'

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: 设置 Python
      uses: actions/setup-python@v1
      with:
        python-version: '3.8'
    - name: 安装依赖
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: 运行脚本
      run: python ${{ github.event.inputs.script_name }}
    - name: 上传 CSV 文件
      uses: actions/upload-artifact@v2
      with:
        name: csv_output
        path: ${{ github.event.inputs.script_name }}_*.csv
